import "server-only";

import placeRecords from "@/lib/location-places.json";
import { LOCATION, placeKey, type LocationPlace } from "@/lib/location";

// One place list, generated by scripts/location/build-places.py.
// GeoNames cities5000 (https://www.geonames.org/), CC BY 4.0.
// Credit: GeoNames. Population floor 5,000. In-process typeahead,
// no paid geocoder key, no client bundle.
// US region is the postal abbreviation (Texas → TX) so the label
// reads "Austin, TX, US". regionName keeps the admin name for search.
// Other regions are admin1 names. No admin1 → country name
// (Hong Kong, Gibraltar). alt is the ascii name when it differs
// from the folded city (search only).

type PlaceRecord = LocationPlace & {
  pop: number;
  regionName?: string;
  alt?: string;
};

const COUNTRY_ALIASES: Record<string, string> = {
  AE: "uae",
  GB: "uk united kingdom",
  KR: "south korea",
  US: "usa united states",
};

const PLACES = placeRecords as PlaceRecord[];

type IndexedPlace = PlaceRecord & { cityFold: string; stack: string };

function fold(value: string): string {
  return value.normalize("NFD").replace(/\p{M}/gu, "").toLowerCase();
}

function collapse(value: string): string {
  return fold(value).replace(/[^a-z0-9]+/g, " ").trim();
}

function haystack(place: PlaceRecord): string {
  return collapse(
    [place.city, place.alt, place.region, place.regionName, place.country, COUNTRY_ALIASES[place.country]]
      .filter((part) => part && part.length > 0)
      .join(" "),
  );
}

const INDEX: IndexedPlace[] = PLACES.map((place) => ({
  ...place,
  cityFold: collapse(place.city),
  stack: haystack(place),
}));

const BY_KEY = new Map<string, PlaceRecord>();
for (const place of PLACES) {
  BY_KEY.set(placeKey(place), place);
}

export function isKnownPlace(place: LocationPlace): boolean {
  return BY_KEY.has(placeKey(place));
}

/** In-process typeahead. Short queries and oversized input return nothing. */
export function searchPlaces(query: string, limit = LOCATION.searchLimit): LocationPlace[] {
  const q = collapse(query);
  if (q.length < LOCATION.searchMin || q.length > 80) return [];
  const cap = Math.max(1, Math.min(limit, LOCATION.searchLimit));
  const hits: { place: IndexedPlace; score: number }[] = [];
  for (const place of INDEX) {
    const city = place.cityFold;
    let score = 0;
    if (city === q) score = 100;
    else if (city.startsWith(q)) score = 80;
    else if (city.includes(q)) score = 60;
    else if (place.stack.includes(q)) score = 40;
    else {
      const tokens = q.split(" ").filter((token) => token.length > 0);
      if (tokens.length > 1 && tokens.every((token) => place.stack.includes(token))) {
        score = city.startsWith(tokens[0] ?? "") ? 50 : 30;
      }
    }
    if (score === 0) continue;
    hits.push({ place, score });
  }
  hits.sort((a, b) => b.score - a.score || b.place.pop - a.place.pop || a.place.city.localeCompare(b.place.city));
  return hits.slice(0, cap).map(({ place }) => ({
    city: place.city,
    region: place.region,
    country: place.country,
  }));
}
